//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Tasks
    {
        public int Audit_id { get; set; }
        public Nullable<int> Nro_movement { get; set; }
        public string Operation_type { get; set; }
        public Nullable<System.DateTime> Operation_date { get; set; }
        public Nullable<int> User_add { get; set; }
        public Nullable<int> Task_id { get; set; }
        public string Task_Title { get; set; }
        public string Task_description { get; set; }
        public Nullable<int> User_respon { get; set; }
        public Nullable<int> Priority_id { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public Nullable<int> State_id { get; set; }
    }
}
