//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Task_id { get; set; }
        public string Task_Title { get; set; }
        public string Task_description { get; set; }
        public int User_respon { get; set; }
        public Nullable<int> Priority_id { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public int State_id { get; set; }
    }
}
