//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Priorities_Tasks
    {
        public int Priority_id { get; set; }
        public Nullable<System.DateTime> Date_add { get; set; }
        public Nullable<System.DateTime> Date_last_upd { get; set; }
        public Nullable<int> User_add { get; set; }
        public Nullable<int> User_last_upd { get; set; }
        public string Priority_description { get; set; }

        public List<Priorities_Tasks> GetList()
        {
            TaskManagerEntities DbContext = new TaskManagerEntities();
            return DbContext.Priorities_Tasks.ToList();
        }
    }
}
