//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Tasks_Progress
    {
        public int Id { get; set; }
        public Nullable<int> State_id { get; set; }
        public string State_description { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> UserID { get; set; }

        public List<Tasks_Progress> GetProgress(int userID)
        {
            TaskManagerEntities DbContext = new TaskManagerEntities();
            return DbContext.GetTasksProgressByUser(1).ToList();
        }
    }
}
