//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TaskManagerEntities : DbContext
    {
        public TaskManagerEntities()
            : base("name=TaskManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Priorities_Tasks> Priorities_Tasks { get; set; }
        public virtual DbSet<States_Tasks> States_Tasks { get; set; }
        public virtual DbSet<Tasks_Progress> Tasks_Progress { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Tasks_Progress> GetTasksProgressByUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tasks_Progress>("GetTasksProgressByUser", useridParameter);
        }
    
        public virtual ObjectResult<Tasks_Progress> GetTasksProgressByUser(Nullable<int> userid, MergeOption mergeOption)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tasks_Progress>("GetTasksProgressByUser", mergeOption, useridParameter);
        }
    }
}
